import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction
import MaleyLean.Papers.NonDegenerateConstructionAndKernelOfAdmissibility
import MaleyLean.Papers.Hodge.AuditRunners

#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperTargetAdequacyForcesKernelRolesStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperConstructionForcesKernelStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperKernelNonDerivabilityStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperNothingDerivableBelowKernelStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperAMetricBoundaryAndNonParameterizationStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.KernelAPlusAuditCertificate.auditSurfaceComplete_holds
#print axioms MaleyLean.Papers.Hodge.EndpointClosure.hodgeEndpoint_of_aascContext
#print axioms MaleyLean.Papers.Hodge.AuditRunners.hodgeAuditRunnerEndpointClosurePercent_eq
